Add command time out hook
badoo/parallel_cucumber pull request #52
Opened 2020-12-09 10:11 UTC by fr0l

2020-12-10 09:54 UTC, rajdeepv commented
this hook, once registered will be called for each command on timeout. Suppose one registered a command timeout hook for batch timeout purpose, it will be called for precheck timeout too (also other commands like setup, teardown etc). This is a bit dangerous

2020-12-14 13:03 UTC, rajdeepv requested changes

2020-12-14 16:44 UTC, fr0l commented on lib/parallel_cucumber/helper/command.rb
> +        def trigger_stacktrace_collection(command_pid, full_script, logger, tree)
fixed. renamed

2020-12-14 16:45 UTC, rajdeepv approved these changes

2020-12-14 16:46 UTC, merged